name: Build

on: [pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                java-version: '11'

            - name: Build with Maven
              run: xvfb-run mvn test